// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBk65M7m5MGv2oOk3TgofRsnHo3sqGlWP0',
    appId: '1:400937935400:web:224894faee939d8926cb1d',
    messagingSenderId: '400937935400',
    projectId: 'cctv-kota-medan-v2-38ffa',
    authDomain: 'cctv-kota-medan-v2-38ffa.firebaseapp.com',
    storageBucket: 'cctv-kota-medan-v2-38ffa.firebasestorage.app',
    measurementId: 'G-FPSHCHWYHT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqiaar6HddJyY1xxIuWaqKm_9Et5E4NUU',
    appId: '1:400937935400:android:5dfac0dd37dd168b26cb1d',
    messagingSenderId: '400937935400',
    projectId: 'cctv-kota-medan-v2-38ffa',
    storageBucket: 'cctv-kota-medan-v2-38ffa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3COoUOCE-YN4m9erGEPftWUXSC-LtFlY',
    appId: '1:400937935400:ios:efb167defa7e884726cb1d',
    messagingSenderId: '400937935400',
    projectId: 'cctv-kota-medan-v2-38ffa',
    storageBucket: 'cctv-kota-medan-v2-38ffa.firebasestorage.app',
    iosBundleId: 'com.example.cctvKotaMedanV2.RunnerTests',
  );
}
